name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Unit Tests
      run: composer test -- --testsuite Unit

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Integration Tests
      run: composer test -- --testsuite Integration

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: composer phpstan

    - name: Run Psalm
      run: composer psalm

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Code Style Check
      run: composer cs-check

    - name: Check Test Results
      if: failure()
      run: |
        echo "::error::Tests failed. Please fix the issues before merging."
        exit 1 